# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
    vb.cpus = "2"
  end

  config.vm.provision "shell" do |s| 
    s.privileged = false
    s.inline = <<-SHELL

      #Install dependencies
      sudo apt-get update
      sudo apt-get -y install python-pip xvfb git libssl-dev phantomjs
      sudo pip install shyaml
      curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.25.4/install.sh | bash
      source /home/vagrant/.bashrc
      sudo su -c  'echo "source /home/vagrant/.nvm/nvm.sh" >> /etc/profile'

      #Install Ruby and travis CLI
      gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
      curl -sSL https://get.rvm.io | sudo bash -s stable --ruby=2.0.0
      source /usr/local/rvm/scripts/rvm
      export rvmsudo_secure_path=1
      rvm gemset use global
      rvmsudo gem install travis bundler --no-rdoc --no-ri

      #Install build plugin for travis CLI
      travis --version --no-interactive
      git clone --depth 1 https://github.com/travis-ci/travis-build.git /home/vagrant/.travis/travis-build
      rvmsudo bundle install --gemfile /home/vagrant/.travis/travis-build/Gemfile --without development test

      #Validate and compile travis.yml into shell script
      cd /vagrant
      travis lint --no-interactive .travis.yml
      travis compile --no-interactive --skip-version-check --skip-completion-check --org > autogenerated_by_travis.sh
      chmod +x autogenerated_by_travis.sh

      #Remove git checkout block from auto-generated script
      FIRST_LINE=$(grep -n "travis_fold start git.checkout" autogenerated_by_travis.sh | awk -F":" '{print $1}')
      LAST_LINE=$(($FIRST_LINE+19))
      EDIT_STRING=$FIRST_LINE,$LAST_LINE"d"
      sed -i -e $EDIT_STRING autogenerated_by_travis.sh

      mkdir $HOME/build
      cp -rv * .meteor/ .travis.yml $HOME/build

      #Run autogenerated script to see how tests might run in the TravisCI environment
      echo "*************************************************************************"
      echo "To run tests, use the auto-generated script that travisCI creates:"
      echo "$HOME/build/autogenerated_by_travis.sh"
      echo "*************************************************************************"

    SHELL
  end
end
